#spring:
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#          min-partition-count: 1
#          auto-create-topics: true
#          auto-add-partitions: true
#      default:
#        group: om # any group assign should not have a '-', otherwise the it cannot be processed;
#        contentType: application/json
#      bindings:
#        mdsReleaseReq:
#          destination: RELEASE-REQ-TEST
#        mdsReleaseRsp:
#          destination: RELEASE-RSP-TEST